#!/bin/bash

scriptname=`basename $0`
cfg=".aws/cross-account-roles"
# provide ARN  of MFA device if it's required by cross account role in this file and  OTP KEY Name used by oauthtool
mfa="$HOME/.aws/mfa"
# source file with MFA variables
source $mfa

if [ -z $1 ]
then
    echo "$scriptname: Service Name Req'd"
    echo ""
    echo "Usage:"
    echo "   $scriptname dev"
    echo "dev - for dev account"
    echo "bapp - for aks account"
    echo "ssrvc - for shared services account"
    echo "mgmt - for management account"
    echo ""
    echo "Configuration: $HOME/$cfg"
    echo "Format: name=aws-cross-account-role|aws-profile"
    exit
fi

awsrole=` grep ^$1 $HOME/$cfg | cut -d"=" -f 2 | cut -d"|" -f 1 | sed "s/ //g" `
awsprofile=` grep ^$1 $HOME/$cfg | cut -d"=" -f 2 | cut -d"|" -f 2 | sed "s/ //g" `

if [ -z "$awsrole" ] || [ -z "$awsprofile" ]
then
    echo "$scriptname: Bad Service Name"
    exit
fi


F=/tmp/aws_cred.txt
C=$(mktemp)
BOTO_CONFIG=$(mktemp)

# I guess it must be unique
SESSION_NAME="mysession$$"
# The most important part
ROLE_ARN="$awsrole"
# use for retrieveing temporary creds if other than default profile should be used
AWSPROFILE="$awsprofile" 


for bin in jq aws oathtool;do 
  which $bin &> /dev/null || { echo "Binary $bin not found. Please install it first." >&2; exit 1; }
done

# 2FA token 
otpkey=` grep ^$MFA $HOME/.otpkeys | cut -d"=" -f 2 | sed "s/ //g" `
if [ -z $otpkey ]
then
    echo "$scriptname: Bad Service Name"
    exit
fi
TOKEN=`/usr/bin/oathtool --totp -b "$otpkey"`
if [ -n "$MFA_ARN" ];then
  aws sts assume-role  --role-arn "$ROLE_ARN" --role-session-name "$SESSION_NAME" --serial-number $MFA_ARN --token-code $TOKEN  | tee $F
else
  aws sts assume-role  --role-arn "$ROLE_ARN" --role-session-name "$SESSION_NAME" --profile "$AWSPROFILE" | tee $F
fi

# unset previous keys
echo 'unset AWS_ACCESS_KEY AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SECRET_KEY AWS_SECURITY_TOKEN' > ${C}

cat $F | jq -r '.Credentials|"export AWS_ACCESS_KEY=" + .AccessKeyId + "\nexport AWS_SECRET_KEY=" + .SecretAccessKey + "\nexport AWS_SECURITY_TOKEN=" + .SessionToken' >> ${C}
# use new keys
. ${C}
echo "export AWS_SECRET_ACCESS_KEY='$AWS_SECRET_KEY'" >> ${C}
echo "export AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY'" >> ${C}
echo "export BOTO_CONFIG=$BOTO_CONFIG" >> ${C}

# create temporary boto profile
cat << EOF > $BOTO_CONFIG
[Credentials]
aws_access_key_id = $AWS_SECRET_KEY
aws_secret_access_key = $AWS_ACCESS_KEY
aws_security_token = $AWS_SECURITY_TOKEN

EOF
chmod 600 $BOTO_CONFIG $F

echo "echo Boto config: $BOTO_CONFIG. Variables exported - now removing $C" >> $C
echo "rm -f $C" >> $C

rm -f ${F}


# sourcing file with new aws credentials
source $C

echo ""
accountalias=`aws iam list-account-aliases --output text`
accountnumber=`aws sts get-caller-identity --output text --query 'Account'`
echo -e "Your switched to the following aws account:"
echo -e "$accountalias"
echo -e "$accountnumber"
echo ""
echo "By default your creds are valid for one hour, after that you need to rerun script"
